### ISSUE TITLE
typescript error of `decimals` in getReserves.ts file

### ISSUE THREAD

**Issue by commonlot** [element-fi/elf-sdk#27]
I found typescript error at this code line:
https://github.com/element-fi/elf-sdk/blob/1d85370eda22d4526799281ca4b5b291990d87a1/src/helpers/getReserves.ts#L56

it should be fixed like this
const decimals: number[] = [];

**Comment by jrhea** [comment]
This shouldn't result in an error, but perhaps your linter doesn't like it.  Easy enough to fix
